version: '3.9'

services:
  elk:
    image: carlesbarreda/elk:latest
    container_name: elk
    hostname: elk
    ports:
      - 5314:5314
    volumes:
      - elk_data:/elk/data
    restart: unless-stopped

volumes:
  elk_data:
    external: true